### ISSUE TITLE
Pirates rate of appearance / immersion

### ISSUE THREAD

**Issue by tukoz** [Faptown/ESPirates#1]
Hey! Having played with Better Vanilla Pirates a couple hundred hours I love the progression and variety going up by ES main storyline BVP add to the game. One thing diminishes game immersion though, are the armadas (re-)appearing every couple systems and minutes whatever I do. E.g:

- a gazillon pirates ships having a party on political and economical main road/systems, like Earth (if during Human space turmoil then fine but otherwise breaks the immersion level)
- after patrolling an area up and forth, depleting it from all pirate ships (at some cost), I take the same road: gazillon pirates are waiting for *us* (WTF?)

While I'm sure it makes fellow players happy as hell (as I do for ~a hour), its artificial level quickly makes the immersion plunges.
Would this be made a setting eventually possible? Or if not, could one edit files like fleets.txt to decrease the relentless pirates fleets rate of appearance? Or accept less Bounty jobs?

**Comment by ZBok** [comment]
Hi buddy, sorry so late reply. 

Are you referring to the Bounty Hunter fleets? The guys that just appear sometimes to mess you up? That shouldn't have been happening, it should be quite a rare event.

**Comment by ZBok** [comment]
Closing as I tried to reproduce this situation and could not. I think the OP was talking about the fleets that attack if you have lots of cargo but no defenses, as this is nothing to do with this plugin

**Comment by tukoz** [comment]
Just as a note and as far as I remember. Back then in end game, I could face and clear as many *pirates* in any given region of space, some more gazillons would appear the next day. While it was fun at first it quickly raised the question "Where do these come from after we cleaned out thousands?" and rather broke the immersion.  
This did not happen yet in my current play-through so it's fine to me that you closed this issue.
